--[[
  figma-fusion-bridge — DaVinci Resolve Lua setup script
  v0.2 (planned — generated by the Figma plugin alongside .comp)

  Run from: DaVinci Resolve > Workspace > Scripts
  or from the Fusion console: dofile("/path/to/setup.lua")

  What v0.2 will do:
  1. Ask user to locate the export folder
  2. Import all PNG assets into the media pool with absolute paths
  3. Load the .comp into a Fusion composition
  4. Fix all Loader node paths
  5. Prompt for footage to wire into VIDEO_PLACEHOLDER nodes
  6. Create timeline track V2 over existing video V1
  7. Place Fusion comp at correct duration

  Status: stub — implementation coming in v0.2
  Repo: https://github.com/Composa-UI/figma-fusion-bridge
]]

local resolve = Resolve()
if not resolve then
  print("[figma-fusion-bridge] Error: could not connect to DaVinci Resolve API.")
  return
end

print("[figma-fusion-bridge] v0.2 Lua setup — coming soon.")
print("For now: open .comp directly in Fusion, replace REPLACE_WITH_VIDEO.mp4 Loader with your footage.")
